##############################################################################
#
#    Questo file e' parte del progetto openpolis.
# 
#    openpolis - la politica trasparente
#    copyright (C) 2008
#    Ass. Democrazia Elettronica e Partecipazione Pubblica, 
#    Via Luigi Montuori 5, 00154 - Roma, Italia
#
#    openpolis e' free software; e' possibile redistribuirlo o modificarlo
#    nei termini della General Public License GNU, versione 2 o successive;
#    secondo quanto pubblicato dalla Free Software Foundation.
#
#    openpolis e' distribuito nella speranza che risulti utile, 
#    ma SENZA ALCUNA GARANZIA.
#    
#    Potete trovare la licenza GPL e altre informazioni su licenze
#    e copyright nella cartella "licenze" del package.
#
#    $HeadURL$
#    $LastChangedDate$
#    $LastChangedBy$
#    $LastChangedRevision$
#
##############################################################################
dev:
  sf_guard_plugin:
    is_social:            on

# default values
all:
  sf_guard_plugin:
    is_social:            off
  
  
  sfSimpleGoogleSitemap:
    orm:                  Propel                 # possible values: auto, Propel, DbFinder. 'auto' is auto detection. Note: case sensitive!
    urls:                                        # define multiple static urls here
      homepage:                                  # just a name
        url:              http://www.openpolis.it    # full URL, e.g.: with http:// prefix
        freq:             weekly                 # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         1.0                    # 1.0 is top priority (100%) compared to 0.2 which is less priority (20%)
    models:                                      # define multiple models to generate sitemap from
      model_regioni:
        model:            OpLocation
        module:           politician
        action:           regPoliticians
        params:                                  # parameters for the url
          location_id: getId                     # name : method to get the parameter value
        date:             getLastChargeUpdate    # method to get date last updated for the url
        criteria:                                # criterias to filter the records to include in the sitemap
          - { column: location_type_id, method: getLocationTypeId, operator: = , value: 4 }
        freq:             weekly                 # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.75                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)
      model_province:
        model:            OpLocation
        module:           politician
        action:           provPoliticians
        params:                                  # parameters for the url
          location_id: getId                     # name : method to get the parameter value
        date:             getLastChargeUpdate    # method to get date last updated for the url
        criteria:                                # criterias to filter the records to include in the sitemap
          - { column: location_type_id, method: getLocationTypeId, operator: = , value: 5 }
        freq:             weekly                 # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.75                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)
      model_comuni:
        model:            OpLocation
        module:           politician
        action:           munPoliticians
        params:                                  # parameters for the url
          location_id: getId                     # name : method to get the parameter value
        date:             getLastChargeUpdate    # method to get date last updated for the url
        criteria:                                # criterias to filter the records to include in the sitemap
          - { column: location_type_id, method: getLocationTypeId, operator: = , value: 6 }
        freq:             weekly                 # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.75                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)
      model_rappresentanti:
        model:            OpLocation
        module:           politician
        action:           forlocation
        params:                                  # parameters for the url
          location_id: getId                     # name : method to get the parameter value
        date:             getLastChargeUpdate    # method to get date last updated for the url
        criteria:                                # criterias to filter the records to include in the sitemap
          - { column: location_type_id, method: getLocationTypeId, operator: = , value: 6 }
        freq:             weekly                 # must be either: always, hourly, daily, weekly, monthly, yearly, never
        priority:         0.75                    # 1.0 is top priority (100%) compared to 0.5 which is less priority (50%)  


  # cookies
  cookies:
    path:                 '/'
    domain:               'openpolis.it'
    sso_name:             'opSSO'
    remember_name:        'opRemember'
    remember_key_expiration_age: 604800


  .values:
    area_for_theme: 
      "0": "Diritti Civili"
      "1": "Giustizia"
      "2": "Economia"
      "3": "Politica estera"
      "4": "Lavoro"
      "5": "Infrastrutture"
      "6": "Riforme Istituzionali"
      "7": "Istruzione e Ricerca"
      "8": "Ambiente"
      "9": "Media e Informazione"
      "10": "Altro"

    position_on_theme:
      "1": "Molto favorevole"
      "2": "Favorevole"
      "3": "Tendenzialmente favorevole"
      "5": "Tendenzialmente contrario"
      "6": "Contrario"
      "7": "Molto contrario"
      
  .global:
    universe:       on
    
    max_spread_mails: 5
    voting_label_theme: 'Prioritario?'
    voting_label_declaration: 'Rilevante?'    
    last_user_contributions: 15
    opinable_content_editable_treshold: 10

  autocomplete:
    min_chars:      3
    limit:          30


  mail:
    attivation_address: http://www.openpolis.it/user/attivation/hash/
    login_address:      http://www.openpolis.it/login
    subject:            registrazione openpolis
    subject2:           attivazione openpolis
    subject3:           openpolis password recovery		
    sender_address:     info@openpolis.it
    sender_name:        Openpolis WebMaster
    from_address:       info@openpolis.it
    from_name:          Openpolis WebMaster
    reply_address:      info@openpolis.it
    reply_name:         Openpolis WebMaster

  pagination:
    limit:              1000
    declaration_limit:  25
    themes_limit:       25
    selectable_declaration_limit: 10
    admin_limit:        20
    search_results:     40
    users:              30

  search:
    max_results: 500

  declarations:
    limit:  10

  query:
    max:            5

  tag:
    cloud_max:      40
    popularity_degrees:  4

  statistics:
    locations_max_users:      5
    
  feed:
    max: 20
    link: http://www.openpolis.it/
    author_name: Openpolis
    author_mail: info@openpolis.it

  utenze_redazionali: "6,8,100,2313,14114,14151"
    
  institution_id:
    CE: 1
    PE: 2
    GI: 3
    CD: 4
    SR: 5
    GR: 6
    CR: 7
    GP: 8
    CP: 9
    GC: 10
    CC: 11
    CO: 12
    PR: 13
    AS: 14

  charge_type_id:
    presidente_repubblica: 19
    presidente: 1
    vicepresidente: 2
    commissario: 3
    pres_comm: 4
    deputato: 5	
    senatore: 6
    pres_consiglio: 7
    senatore_vita: 20
    assessore: 12
    sottosegretario: 11
    sindaco:  14
    commissario_straordinario: 16
    iscritto: 17
    carica:   18
    membro:   23
  party_type:
    main:      1
    secondary: 2
    regional:  3
    death:     4

  location_id:
    europe: 1
    italy:  2

  location_type_id:
    european:   2
    national:   3
    region:     4
    provincial: 5
    municipal:  6

  resource_type:
    official_mail:   1
    unofficial_mail: 2
    official_url:    3
    unofficial_url:  4

  election_type:
    europa:   1
    camera:   2
    senato:   3

  education_level:
    elementare:   3
    media:        4
    superiore:    5
    laurea_breve: 6
    laurea:       7    
   
  color_tonality:
    level_1:      3  #più intenso
    level_2:      2
    level_3:      1
    level_4:      5
    level_5:      4  #meno intenso
    
  imageclass:
    medium:       91
    thumb:        41
    microthumb:   25
