test:
  propel:
    class:          sfPropelDatabase
    param:
      encoding:     utf8
      dsn:          mysql://root@localhost/op_openpolis_test
      persistent:   true

all:
  propel:
    class:          sfPropelDatabase
    param:
      encoding:     utf8
      dsn:          mysql://root@localhost/op_openpolis
      persistent:   true
