generator:
  class:              sfBatchablePropelAdminGenerator
  param:
    model_class:      OpImportModifications
    theme:            batchable
    css:              my_generator

    fields:
      csv_rec:          { name: 'Record CSV' }
      context_filter:   { name: "Seleziona il contesto" }
      import_filter:    { name: "Seleziona l'import" }
      location_filter:  { name: "Seleziona la localit&agrave;" }
      status_filter:    { name: "Seleziona lo status" }
      concretised_at:   { name: "DB"}
    list:
      title:          "Incarichi da chiudere"
      display:        [_csv]
      max_per_page:   15	  
      object_actions:
        reject: { name: 'Respingi', action: 'reject', icon: '/images/admin_icons/disable.png'}
        restore: { name: 'Ripristina', action: 'restore', icon: '/images/admin_icons/button_ok.png'}
        concretise: { name: 'Aggiungi al DB', action: 'concretise', icon: '/images/admin_icons/run.png'}

      filters:        [_importFilter, _contextFilter, _locationFilter, _statusFilter]
      actions:
        concretise: { name: 'Chiudi incarico', action: 'concretiseAll', icon: '/images/admin_icons/remove.png'}
        
      batch_actions:
        rejectSelection:        { name: Rifiuta i selezionati, action: rejectSelection }
        restoreSelection:       { name: Ripristina i selezionati, action: restoreSelection }
        concretiseSelection:       { name: Chiudi gli incarichi, action: concretiseSelection }
